<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accepted usernames arestandard_userlock_0ab16f</name>
   <tag></tag>
   <elementGuidId>ed5504b4-85d3-463b-9c35-115a20b018f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_credentials']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_credentials</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bcf65de-c052-4601-b8aa-024b7ca452ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>23f380db-b416-4f11-aebe-45605c2925ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_credentials</value>
      <webElementGuid>40a08fa5-3739-49a7-9a99-f88bc5727280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_user</value>
      <webElementGuid>adb09cf8-3a0f-4079-8781-c2e651090ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_credentials&quot;)</value>
      <webElementGuid>339bd7d5-9799-42b5-b8d1-8da7498df935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login_credentials']</value>
      <webElementGuid>4ef3d21a-9cca-40a6-95d7-28135a7711cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>9a3c240d-c012-434f-9798-5cb46328c491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='standard_user']/parent::*</value>
      <webElementGuid>6b6b9280-c6f8-4a88-8a85-6221bb90e316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>24070166-403b-4c09-9c21-5d32f2157c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login_credentials' and (text() = 'Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_user' or . = 'Accepted usernames are:standard_userlocked_out_userproblem_userperformance_glitch_user')]</value>
      <webElementGuid>ed7316f4-0089-4723-9ab6-7a3637a7440f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
